site_name: Tower Computers
site_url: https://towercomputers.github.io/tower-tools/
theme:
  name: material
nav:
  - Home: index.md
  - Hardware requirements: hardware.md
  - Installation: installation.md
  - Usage: usage.md
  - Security: security.md
  - Implementation: implementation.md
  - Development: DeveloperGuide.md
  - Whitepaper: "Tower Whitepaper.pdf"