site_name: Documentation
site_url: https://toweros.org
repo_url: https://github.com/towercomputers/toweros/
repo_name: TowerOS
docs_dir: src
markdown_extensions:
    - attr_list
    - md_in_html
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.instant.prefetch
  logo: img/tower-logo.png
  favicon: img/favicon.ico
  icon:
    repo: fontawesome/brands/github
  font: false
extra_css:
    - css/towerdoc.css
nav:
  - Getting Started:
    - Introduction: index.md
    - Hardware: hardware.md
    - Installation and Upgrades: installation.md
  - Usage:
    - Using TowerOS: usage.md
    - Guides: guides.md
    - Tower CLI Manual: manual.md
  - Security:
    - Security: security.md
    - Secure Boot: secure-boot.md
  - Technical:
    - Whitepaper: "TowerOS Whitepaper.pdf"
    - Implementation: implementation.md
    - GitHub Repository: https://github.com/towercomputers/toweros
  - Development:
    - Developer Environment: dev-environment.md
    - Building TowerOS: build-toweros.md
    - QA Script: qa-script.md

extra:
  generator: false
