site_name: TowerOS
site_url: https://toweros.org
docs_dir: src
markdown_extensions:
    - attr_list
    - md_in_html
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.instant.prefetch
nav:
  - Getting Started:
    - Introduction: index.md
    - Hardware: hardware.md
    - Installation and upgrade: installation.md
    - Usage: usage.md
    - Guides: guides.md
  - Security:
    - Security: security.md
    - Secure Boot: secure-boot.md
  - Technical:
    - Whitepaper: "TowerOS Whitepaper.pdf"
    - Implementation: implementation.md
    - Development: development.md
    - GitHub Repository: https://github.com/towercomputers/toweros

extra:
  generator: false
